// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS76kjS_gl1bRvQX6Qvgq4dbMb6qGGCqg',
    appId: '1:915183794295:web:e022f5394265a7f785ae72',
    messagingSenderId: '915183794295',
    projectId: 'comizy',
    authDomain: 'comizy.firebaseapp.com',
    storageBucket: 'comizy.firebasestorage.app',
    measurementId: 'G-J8P5YNYRS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGRgrrvx-3aGDLsMRYSJY6_H6noz1qOk',
    appId: '1:915183794295:android:5a26089a30b6358485ae72',
    messagingSenderId: '915183794295',
    projectId: 'comizy',
    storageBucket: 'comizy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdniuziEq211-wccMB2rv_Pi4P0KKZZpc',
    appId: '1:915183794295:ios:871fee91fd47704385ae72',
    messagingSenderId: '915183794295',
    projectId: 'comizy',
    storageBucket: 'comizy.firebasestorage.app',
    iosBundleId: 'com.comizy.comizy',
  );
}
